[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://declanbyrd-speedlify.netlify.app"
  to = "https://speedlify.declanbyrd.co.uk"
  status = 301
  force = true
